### ISSUE TITLE
Error when computing top 10 bigrams in corpus

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/dask#269]
When trying to find topk bigrams in my text corpus:

```python
b.pluck('abstract').str.split().map(lambda l: list(sliding_window(2, l))).concat().frequencies().topk(10, key=1).compute()
```

I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-78-03445e41555d> in <module>()
----> 1 b.pluck('abstract').str.split().map(lambda l: list(sliding_window(2, l))).concat().frequencies().topk(10, key=1).compute()

/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/bag/core.pyc in compute(self, **kwargs)
    570     def compute(self, **kwargs):
    571         """ Force evaluation of bag """
--> 572         results = get(self.dask, self._keys(), **kwargs)
    573         if isinstance(results[0], Iterable):
    574             results = toolz.concat(results)

/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/bag/core.pyc in get(dsk, keys, get, **kwargs)
     82     dsk2 = optimize(dsk, keys)
     83 
---> 84     return get(dsk2, keys, **kwargs)
     85 _get = get
     86 

/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/multiprocessing.pyc in get(dsk, keys, optimizations, num_workers, func_loads, func_dumps)
     49         # Run
     50         result = get_async(apply_async, len(pool._pool), dsk2, keys,
---> 51                            queue=queue)
     52     finally:
     53         if cleanup:

/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, debug_counts, queue, raise_on_exception, **kwargs)
    445         if isinstance(res, Exception):
    446             raise type(res)(" Exception in remote process\n\n"
--> 447                 + str(res) + "\n\nTraceback:\n" + tb)
    448         state['cache'][key] = res
    449         finish_task(dsk, key, state, results)

TypeError:  Exception in remote process



Traceback:
  File "/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/async.py", line 258, in execute_task
    result = _execute_task(task, data)
  File "/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/async.py", line 240, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/Users/cdoig/anaconda/envs/dask-tokenize/lib/python2.7/site-packages/dask/async.py", line 241, in _execute_task
    return func(*args2)
  File "cytoolz/functoolz.pyx", line 256, in cytoolz.functoolz.curry.__call__ (cytoolz/functoolz.c:3300)
    raise val
```

**Comment by eriknw** [comment]
`heapq.nlargest` (used by `dask.Bag.topk`) expects a callable for the `key` parameter.  `toolz.topk` can accept a callable, index, or list of indices as `key`.  Maybe we should switch to `toolz.topk`.

**Comment by mrocklin** [comment]
Indeed.  This was actually the original use case for why I wanted `toolz.topk`.  I'll get around to this sometime today.
