### ISSUE TITLE
dask.array aggregation results compute as scalars, not 0d arrays

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/dask#391]
On Python 2.7:
```
In [11]: da.mean(da.ones(4, chunks=4), axis=0)
Out[11]: dask.array<x_16, shape=(), chunks=(), dtype=float64>

In [9]: type(da.mean(da.ones(4, chunks=4), axis=0).compute())
Out[9]: numpy.float64
```

On Python 3.4:
```
In [4]: type(da.mean(da.ones(4, chunks=4), axis=0).compute())
Out[4]: float
```

For consistency between the pre- and post-computed results, these should arguably both be 0-dimensional numpy arrays, because there are no dask.array scalars (maybe there should be?). At the very least, the result should be the same type on both Python versions.

Why this is a problem? `float` cannot be indexed with `None`, which is used in `da.stack`:
```
# python 3.4
In [14]: x = da.ones(4, chunks=4)

In [15]: da.stack([x.mean(), x.mean()])
Out[15]: dask.array<stack-6, shape=(2,), chunks=((1, 1)), dtype=float64>

In [16]: da.stack([x.mean(), x.mean()]).compute()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-52554981f590> in <module>()
----> 1 da.stack([x.mean(), x.mean()]).compute()

/Users/shoyer/dev/dask/dask/array/core.py in compute(self, **kwargs)
    721     @wraps(compute)
    722     def compute(self, **kwargs):
--> 723         result, = compute(self, **kwargs)
    724         return result
    725

/Users/shoyer/dev/dask/dask/array/core.py in compute(*args, **kwargs)
    511     dsk = merge(*[arg.dask for arg in args])
    512     keys = [arg._keys() for arg in args]
--> 513     results = get(dsk, keys, **kwargs)
    514
    515     results2 = tuple(concatenate3(x) if arg.shape else unpack_singleton(x)

/Users/shoyer/dev/dask/dask/array/core.py in get(dsk, keys, get, **kwargs)
   1242     get = get or _globals['get'] or threaded.get
   1243     dsk2 = optimize(dsk, keys, **kwargs)
-> 1244     return get(dsk2, keys, **kwargs)
   1245
   1246

/Users/shoyer/dev/dask/dask/threaded.py in get(dsk, result, cache, **kwargs)
     52     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     53                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 54                         **kwargs)
     55
     56     return results

/Users/shoyer/dev/dask/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, start_callback, end_callback, **kwargs)
    460         if isinstance(res, Exception):
    461             raise type(res)(" Exception in remote process\n\n"
--> 462                 + str(res) + "\n\nTraceback:\n" + tb)
    463         state['cache'][key] = res
    464         finish_task(dsk, key, state, results)

TypeError:  Exception in remote process

'float' object is not subscriptable

Traceback:
  File "/Users/shoyer/dev/dask/dask/async.py", line 260, in execute_task
    result = _execute_task(task, data)
  File "/Users/shoyer/dev/dask/dask/async.py", line 243, in _execute_task
    return func(*args2)
  File "/Users/shoyer/dev/dask/dask/array/core.py", line 41, in getarray
    c = a[b]
```

This is the cause of recent build failures in xray on Python 3.4.

**Comment by teoliphant** [comment]
My recommendation is to leave them as 0-dimensional arrays.
